return `/* settingsPlugin-styles.css
 * Windrose MapDesigner Settings Plugin Styles
 * This file is automatically loaded by Obsidian when the plugin is enabled.
 * Generated by settingsPluginAssembler.js
 */

/* ===========================================
 * Subheadings
 * =========================================== */
.dmt-settings-subheading {
  font-size: 14px;
  font-weight: 600;
  color: var(--text-muted);
  margin: 1.5em 0 0.5em 0;
  padding-bottom: 4px;
  border-bottom: 1px solid var(--background-modifier-border);
}

/* ===========================================
 * Search/Filter
 * =========================================== */
.dmt-settings-search-container {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 1em;
}

.dmt-settings-search-input {
  flex: 1;
  padding: 8px 12px;
  border: 1px solid var(--background-modifier-border);
  border-radius: 4px;
  background: var(--background-primary);
  font-size: 14px;
}

.dmt-settings-search-input:focus {
  border-color: var(--interactive-accent);
  outline: none;
}

.dmt-settings-search-clear {
  background: transparent;
  border: none;
  padding: 6px;
  border-radius: 4px;
  cursor: pointer;
  color: var(--text-muted);
  display: flex;
  align-items: center;
  justify-content: center;
}

.dmt-settings-search-clear:hover {
  background: var(--background-modifier-hover);
  color: var(--text-normal);
}

.dmt-settings-no-results {
  text-align: center;
  padding: 2em;
  color: var(--text-muted);
  font-style: italic;
}

/* ===========================================
 * Category Containers
 * =========================================== */
.dmt-settings-category {
  margin: 1em 0;
  border: 1px solid var(--background-modifier-border);
  border-radius: 8px;
  overflow: hidden;
}

.dmt-settings-category-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 12px;
  background: var(--background-secondary);
  border-bottom: 1px solid var(--background-modifier-border);
}

.dmt-settings-category-label {
  font-weight: 600;
  font-size: 0.95em;
}

.dmt-settings-category-actions {
  display: flex;
  gap: 4px;
}

.dmt-settings-category-muted {
  opacity: 0.7;
}

.dmt-settings-empty-message {
  padding: 16px;
  text-align: center;
  color: var(--text-muted);
  font-style: italic;
}

/* ===========================================
 * Object Rows
 * =========================================== */
.dmt-settings-object-list {
  padding: 4px 0;
}

.dmt-settings-object-row {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
  transition: background-color 0.15s ease;
}

.dmt-settings-object-row:hover {
  background: var(--background-modifier-hover);
}

.dmt-drag-handle {
  color: var(--text-muted);
  cursor: grab;
  padding: 0 4px;
  font-size: 1em;
  opacity: 0.4;
  user-select: none;
  flex-shrink: 0;
}

.dmt-settings-object-row:hover .dmt-drag-handle {
  opacity: 1;
}

.dmt-dragging {
  opacity: 0.5;
  background: var(--interactive-accent) !important;
  border-radius: 4px;
}

.dmt-settings-object-symbol {
  font-family: 'Noto Emoji', 'Noto Sans Symbols 2', sans-serif;
  font-size: 1.4em;
  width: 32px;
  text-align: center;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}

.dmt-settings-object-symbol .ra {
  font-size: 1.2em;
  line-height: 1;
}

.dmt-settings-object-label {
  flex: 1;
  min-width: 0;
}

.dmt-settings-object-label.dmt-settings-modified {
  font-style: italic;
  color: var(--text-accent);
}

.dmt-settings-object-label.dmt-settings-modified::after {
  content: ' •';
  font-size: 0.8em;
  opacity: 0.7;
}

.dmt-settings-object-actions {
  display: flex;
  gap: 4px;
  flex-shrink: 0;
}

/* ===========================================
 * Icon Buttons
 * =========================================== */
.dmt-settings-icon-btn {
  background: transparent;
  border: none;
  padding: 4px 6px;
  border-radius: 4px;
  cursor: pointer;
  color: var(--text-muted);
  display: flex;
  align-items: center;
  justify-content: center;
}

.dmt-settings-icon-btn:hover {
  background: var(--background-modifier-hover);
  color: var(--text-normal);
}

.dmt-settings-icon-btn-danger:hover {
  color: var(--text-error);
}

.dmt-btn-icon {
  background: transparent;
  border: none;
  padding: 4px;
  border-radius: 4px;
  cursor: pointer;
  color: var(--text-muted);
  display: flex;
  align-items: center;
  justify-content: center;
}

.dmt-btn-icon:hover {
  background: var(--background-modifier-hover);
  color: var(--text-normal);
}

.dmt-btn-icon.dmt-btn-danger:hover {
  background: var(--background-modifier-error);
  color: var(--text-on-accent);
}

/* ===========================================
 * Hidden Section
 * =========================================== */
.dmt-settings-hidden-section {
  margin-top: 2em;
  padding-top: 1em;
  border-top: 1px solid var(--background-modifier-border);
}

.dmt-settings-hidden-list {
  margin-top: 8px;
  opacity: 0.7;
}

.dmt-settings-hidden-list .dmt-settings-object-row {
  background: var(--background-secondary);
}

/* ===========================================
 * Modal Base Styles
 * =========================================== */
.dmt-object-edit-modal,
.dmt-category-edit-modal {
  padding: 0;
}

.dmt-modal-buttons {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  margin-top: 1.5em;
  padding-top: 1em;
  border-top: 1px solid var(--background-modifier-border);
}

/* ===========================================
 * Symbol Input & Preview
 * =========================================== */
.dmt-symbol-input {
  font-family: 'Noto Emoji', 'Noto Sans Symbols 2', sans-serif;
  font-size: 1.5em;
  width: 80px;
  text-align: center;
  padding: 8px;
}

.dmt-symbol-preview {
  font-family: 'Noto Emoji', 'Noto Sans Symbols 2', sans-serif;
  font-size: 2em;
  width: 48px;
  height: 48px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--background-secondary);
  border-radius: 8px;
  margin-left: 8px;
}

/* ===========================================
 * Quick Symbols Grid
 * =========================================== */
.dmt-quick-symbols {
  margin: 1em 0;
}

.dmt-quick-symbols-label {
  display: block;
  font-size: 0.9em;
  color: var(--text-muted);
  margin-bottom: 8px;
}

.dmt-quick-symbols-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  max-height: 150px;
  overflow-y: auto;
  padding: 4px;
  background: var(--background-secondary);
  border-radius: 8px;
}

.dmt-quick-symbol-btn {
  font-family: 'Noto Emoji', 'Noto Sans Symbols 2', sans-serif;
  width: 32px;
  height: 32px;
  font-size: 1.2em;
  border: 1px solid var(--background-modifier-border);
  background: var(--background-primary);
  border-radius: 4px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
}

.dmt-quick-symbol-btn:hover {
  background: var(--background-modifier-hover);
  border-color: var(--interactive-accent);
}

/* ===========================================
 * Import/Export Modal Styles
 * =========================================== */
.dmt-export-modal,
.dmt-import-modal {
  padding: 0;
}

.dmt-export-empty {
  text-align: center;
  padding: 1em;
  color: var(--text-muted);
  font-style: italic;
}

.dmt-import-file-container {
  margin: 1em 0;
}

.dmt-import-file-container input[type="file"] {
  width: 100%;
  padding: 1em;
  border: 2px dashed var(--background-modifier-border);
  border-radius: 8px;
  background: var(--background-secondary);
  cursor: pointer;
}

.dmt-import-file-container input[type="file"]:hover {
  border-color: var(--interactive-accent);
}

.dmt-import-preview {
  margin: 1em 0;
  padding: 1em;
  background: var(--background-secondary);
  border-radius: 8px;
}

.dmt-import-preview p {
  margin: 0.25em 0;
}

.dmt-import-date {
  font-size: 0.85em;
  color: var(--text-muted);
}

.dmt-import-note {
  font-size: 0.9em;
  color: var(--text-muted);
  font-style: italic;
}

.dmt-import-error {
  color: var(--text-error);
  font-weight: 500;
}

.dmt-import-options {
  margin-top: 1em;
}

/* ===========================================
 * Icon Type Toggle
 * =========================================== */
.dmt-icon-type-toggle {
  display: flex;
  gap: 8px;
  margin-bottom: 1em;
}

.dmt-icon-type-btn {
  flex: 1;
  padding: 8px 12px;
  border: 1px solid var(--background-modifier-border);
  background: var(--background-primary);
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  transition: all 0.15s ease;
}

.dmt-icon-type-btn:hover {
  background: var(--background-modifier-hover);
}

.dmt-icon-type-btn.active {
  background: var(--interactive-accent);
  color: var(--text-on-accent);
  border-color: var(--interactive-accent);
}

/* ===========================================
 * Icon Picker Container
 * =========================================== */
.dmt-icon-picker {
  border: 1px solid var(--background-modifier-border);
  border-radius: 8px;
  background: var(--background-secondary);
  margin-bottom: 1em;
}

.dmt-icon-picker-search {
  padding: 8px;
  border-bottom: 1px solid var(--background-modifier-border);
}

.dmt-icon-picker-search input {
  width: 100%;
  padding: 6px 10px;
  border: 1px solid var(--background-modifier-border);
  border-radius: 4px;
  background: var(--background-primary);
  font-size: 14px;
}

.dmt-icon-picker-search input:focus {
  border-color: var(--interactive-accent);
  outline: none;
}

/* ===========================================
 * Category Tabs (Icon Picker)
 * =========================================== */
.dmt-icon-picker-tabs {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  padding: 8px;
  border-bottom: 1px solid var(--background-modifier-border);
  background: var(--background-primary-alt);
}

.dmt-icon-picker-tab {
  padding: 4px 8px;
  border: 1px solid transparent;
  background: transparent;
  border-radius: 4px;
  cursor: pointer;
  font-size: 12px;
  color: var(--text-muted);
  transition: all 0.15s ease;
}

.dmt-icon-picker-tab:hover {
  background: var(--background-modifier-hover);
  color: var(--text-normal);
}

.dmt-icon-picker-tab.active {
  background: var(--interactive-accent);
  color: var(--text-on-accent);
}

/* ===========================================
 * Icon Grid
 * =========================================== */
.dmt-icon-picker-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(40px, 1fr));
  gap: 4px;
  padding: 8px;
  max-height: 200px;
  overflow-y: auto;
}

.dmt-icon-picker-icon {
  width: 40px;
  height: 40px;
  border: 1px solid var(--background-modifier-border);
  background: var(--background-primary);
  border-radius: 4px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 20px;
  transition: all 0.15s ease;
}

.dmt-icon-picker-icon:hover {
  background: var(--background-modifier-hover);
  border-color: var(--interactive-accent);
  transform: scale(1.1);
}

.dmt-icon-picker-icon.selected {
  background: var(--interactive-accent);
  color: var(--text-on-accent);
  border-color: var(--interactive-accent);
}

.dmt-icon-picker-icon .ra {
  font-size: 20px;
  line-height: 1;
}

.dmt-icon-picker-empty {
  padding: 2em;
  text-align: center;
  color: var(--text-muted);
  font-style: italic;
}

/* ===========================================
 * Selected Icon Preview
 * =========================================== */
.dmt-icon-preview-row {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 8px;
  border-top: 1px solid var(--background-modifier-border);
  background: var(--background-primary);
}

.dmt-icon-preview-large {
  width: 48px;
  height: 48px;
  border: 1px solid var(--background-modifier-border);
  border-radius: 4px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 28px;
  background: var(--background-secondary);
}

.dmt-icon-preview-large .ra {
  font-size: 28px;
  line-height: 1;
}

.dmt-icon-preview-info {
  flex: 1;
}

.dmt-icon-preview-label {
  font-weight: 500;
  margin-bottom: 2px;
}

.dmt-icon-preview-class {
  font-size: 12px;
  color: var(--text-muted);
  font-family: var(--font-monospace);
}

/* ===========================================
 * RPGAwesome Icon Font
 * Font-family name must be exactly 'rpgawesome'
 * Font is bundled in DungeonMapTracker FONTS.css
 * =========================================== */
.ra {
  font-family: 'rpgawesome' !important;
  font-style: normal;
  font-variant: normal;
  font-weight: normal;
  line-height: 1;
  speak: never;
  text-transform: none;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

/* ===========================================
 * Collapsible Sections
 * =========================================== */
.dmt-settings-section {
  margin: 0 0 8px 0;
  border: 1px solid var(--background-modifier-border);
  border-radius: 6px;
  overflow: hidden;
}

.dmt-settings-section > summary {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 16px;
  background: var(--background-secondary);
  cursor: pointer;
  font-weight: 600;
  font-size: 15px;
  list-style: none;
  user-select: none;
}

.dmt-settings-section > summary::-webkit-details-marker {
  display: none;
}

.dmt-settings-section > summary::before {
  content: '▶';
  font-size: 10px;
  transition: transform 0.2s ease;
  color: var(--text-muted);
}

.dmt-settings-section[open] > summary::before {
  transform: rotate(90deg);
}

.dmt-settings-section > summary:hover {
  background: var(--background-modifier-hover);
}

.dmt-settings-section-content {
  padding: 12px 16px;
  border-top: 1px solid var(--background-modifier-border);
}

.dmt-settings-section-content > .setting-item:first-child {
  border-top: none;
  padding-top: 0;
}

/* ===========================================
 * Settings Search
 * =========================================== */
.dmt-settings-search-wrapper {
  margin-bottom: 16px;
  position: sticky;
  top: 0;
  background: var(--background-primary);
  padding: 8px 0;
  z-index: 10;
}

.dmt-settings-search-box {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  border: 1px solid var(--background-modifier-border);
  border-radius: 6px;
  background: var(--background-primary);
}

.dmt-settings-search-box:focus-within {
  border-color: var(--interactive-accent);
}

.dmt-settings-search-box input {
  flex: 1;
  border: none;
  background: transparent;
  font-size: 14px;
  outline: none;
}

.dmt-settings-search-box .search-icon {
  color: var(--text-muted);
}

.dmt-settings-search-box .clear-btn {
  background: transparent;
  border: none;
  padding: 2px 6px;
  cursor: pointer;
  color: var(--text-muted);
  border-radius: 4px;
}

.dmt-settings-search-box .clear-btn:hover {
  background: var(--background-modifier-hover);
  color: var(--text-normal);
}

/* Hide non-matching settings during search */
.dmt-setting-hidden {
  display: none !important;
}

/* Highlight matching text */
.dmt-search-match {
  background: var(--text-highlight-bg);
  border-radius: 2px;
}

/* ===========================================
 * Color Palette Section
 * =========================================== */
.dmt-color-list {
  padding: 8px 0;
}

.dmt-color-row {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 8px 12px;
  transition: background-color 0.15s ease;
}

.dmt-color-row:hover {
  background: var(--background-modifier-hover);
}

.dmt-color-row-swatch {
  width: 28px;
  height: 28px;
  border-radius: 4px;
  border: 2px solid var(--background-modifier-border);
  flex-shrink: 0;
}

.dmt-color-row-label {
  flex: 1;
  min-width: 0;
}

.dmt-color-row-name {
  font-weight: 500;
}

.dmt-color-row-modified,
.dmt-color-row-custom {
  font-size: 0.85em;
  color: var(--text-muted);
  font-style: italic;
}

.dmt-color-row-hex {
  font-size: 0.85em;
  color: var(--text-muted);
  background: var(--background-secondary);
  padding: 2px 6px;
  border-radius: 3px;
}

.dmt-color-row-actions {
  display: flex;
  gap: 4px;
  flex-shrink: 0;
}

/* ===========================================
 * Color Edit Modal
 * =========================================== */
.dmt-color-edit-modal {
  padding: 16px;
}

.dmt-color-hex-input {
  font-family: var(--font-monospace);
  width: 90px !important;
}

.dmt-color-original-info {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 8px 12px;
  margin: 12px 0;
  background: var(--background-secondary);
  border-radius: 4px;
  font-size: 0.9em;
  color: var(--text-muted);
}

.dmt-color-mini-swatch {
  display: inline-block;
  width: 16px;
  height: 16px;
  border-radius: 3px;
  border: 1px solid var(--background-modifier-border);
  vertical-align: middle;
}

.dmt-opacity-control {
  display: flex;
  align-items: center;
  gap: 8px;
}

.dmt-opacity-control input[type="range"] {
  width: 120px;
}

.dmt-opacity-value {
  min-width: 40px;
  text-align: right;
  font-size: 0.9em;
  color: var(--text-muted);
}

/* ===========================================
 * Insert Map Modal
 * =========================================== */
.dmt-insert-map-modal {
  padding: 16px;
}

.dmt-map-type-selection {
  margin-top: 16px;
}

.dmt-map-type-buttons {
  display: flex;
  gap: 8px;
  margin-top: 8px;
}

.dmt-map-type-btn {
  flex: 1;
  padding: 12px 16px;
  border: 2px solid var(--background-modifier-border);
  border-radius: 6px;
  background: var(--background-primary);
  color: var(--text-normal);
  cursor: pointer;
  font-size: 1em;
  transition: all 0.15s ease;
}

.dmt-map-type-btn:hover {
  border-color: var(--interactive-accent);
  background: var(--background-secondary);
}

.dmt-map-type-btn.selected {
  border-color: var(--interactive-accent);
  background: var(--interactive-accent);
  color: var(--text-on-accent);
}

/* ===========================================
 * Insert Dungeon Modal
 * =========================================== */
.dmt-insert-dungeon-modal {
  padding: 16px;
  min-width: 400px;
}

/* Soften the modal container's border and shadow */
.modal:has(.dmt-insert-dungeon-modal) {
  border: 1px solid var(--background-modifier-border);
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.25);
}

/* Header with Visualizer */
.dmt-dungeon-header {
  position: relative;
  margin: -16px -16px 0 -16px; /* Extend to modal edges, no bottom margin */
  overflow: hidden;
}

.dmt-dungeon-visualizer {
  width: 100%;
  height: 180px;
  position: relative;
}

.dmt-dungeon-visualizer canvas {
  display: block;
}

.dmt-dungeon-title-overlay {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  padding: 20px 16px 8px 16px;
  background: linear-gradient(to bottom, transparent 0%, var(--modal-background) 60%);
}

.dmt-dungeon-title-overlay h2 {
  margin: 0;
  font-size: 1.3em;
  color: var(--text-normal);
}

/* Space after header before first setting - this also serves as visual separator */
.dmt-dungeon-header + .setting-item {
  margin-top: 16px;
  border-top: none !important;
}

/* Stamp animation for visualizer */
@keyframes dmt-windrose-stamp {
  0% {
    transform: translate(-50%, -50%) scale(1.6) rotate(-18deg);
    opacity: 0;
  }
  50% {
    opacity: 0.8;
  }
  100% {
    transform: translate(-50%, -50%) scale(1) rotate(0deg);
    opacity: 0.75;
  }
}

.dmt-dungeon-size-selection {
  margin-top: 16px;
}

.dmt-dungeon-size-buttons {
  display: flex;
  gap: 8px;
  margin-top: 8px;
  flex-wrap: wrap;
}

.dmt-dungeon-size-btn {
  flex: 1;
  padding: 12px 16px;
  border: 2px solid var(--background-modifier-border);
  border-radius: 6px;
  background: var(--background-primary);
  color: var(--text-normal);
  cursor: pointer;
  font-size: 1em;
  font-weight: 500;
  transition: all 0.15s ease;
  text-align: center;
}

.dmt-dungeon-size-btn:hover {
  border-color: var(--interactive-accent);
  background: var(--background-secondary);
}

.dmt-dungeon-size-btn.selected {
  border-color: var(--interactive-accent);
  background: var(--interactive-accent);
  color: var(--text-on-accent);
}

.dmt-dungeon-style-selection {
  margin-top: 16px;
}

.dmt-dungeon-style-buttons {
  display: flex;
  gap: 8px;
  margin-top: 8px;
  flex-wrap: wrap;
}

.dmt-dungeon-style-btn {
  flex: 1;
  min-width: 70px;
  padding: 10px 12px;
  border: 2px solid var(--background-modifier-border);
  border-radius: 6px;
  background: var(--background-primary);
  color: var(--text-normal);
  cursor: pointer;
  font-size: 0.9em;
  font-weight: 500;
  transition: all 0.15s ease;
  text-align: center;
}

.dmt-dungeon-style-btn:hover {
  border-color: var(--interactive-accent);
  background: var(--background-secondary);
}

.dmt-dungeon-style-btn.selected {
  border-color: var(--interactive-accent);
  background: var(--interactive-accent);
  color: var(--text-on-accent);
}

.dmt-dungeon-distance-row {
  display: flex;
  gap: 8px;
  align-items: center;
  margin-top: 8px;
}

.dmt-dungeon-distance-row input[type="number"] {
  width: 80px;
}

.dmt-dungeon-distance-row input[type="text"] {
  width: 60px;
}

/* Advanced options section */
.dmt-dungeon-advanced {
  margin-top: 16px;
  border: 1px solid var(--background-modifier-border);
  border-radius: 6px;
  overflow: hidden;
}

.dmt-dungeon-advanced-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 12px;
  background: var(--background-secondary);
  cursor: pointer;
  user-select: none;
  font-weight: 500;
}

.dmt-dungeon-advanced-header:hover {
  background: var(--background-modifier-hover);
}

.dmt-dungeon-advanced-chevron {
  font-size: 0.75em;
  color: var(--text-muted);
}

.dmt-dungeon-advanced-content {
  padding: 12px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.dmt-dungeon-slider-row {
  display: flex;
  align-items: center;
  gap: 12px;
}

.dmt-dungeon-slider-row label {
  flex: 0 0 130px;
  font-size: 0.9em;
  color: var(--text-normal);
}

.dmt-dungeon-slider-container {
  flex: 1;
  display: flex;
  align-items: center;
  gap: 10px;
}

.dmt-dungeon-slider-container input[type="range"] {
  flex: 1;
  height: 4px;
  -webkit-appearance: none;
  appearance: none;
  background: var(--background-modifier-border);
  border-radius: 2px;
  cursor: pointer;
}

.dmt-dungeon-slider-container input[type="range"]::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: var(--interactive-accent);
  cursor: pointer;
}

.dmt-dungeon-slider-container input[type="range"]::-moz-range-thumb {
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: var(--interactive-accent);
  border: none;
  cursor: pointer;
}

.dmt-dungeon-slider-value {
  flex: 0 0 60px;
  text-align: right;
  font-size: 0.85em;
  color: var(--text-muted);
  font-family: var(--font-monospace);
}

.dmt-dungeon-toggle-container {
  flex: 1;
  display: flex;
  align-items: center;
}

.dmt-dungeon-select {
  padding: 4px 8px;
  border: 1px solid var(--background-modifier-border);
  border-radius: 4px;
  background: var(--background-primary);
  color: var(--text-normal);
  font-size: 0.9em;
  cursor: pointer;
}

/* ===========================================
 * Dungeon Modal Section Headers
 * =========================================== */
.dmt-dungeon-section-header {
  font-size: 0.85em;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  margin-top: 16px;
  padding-top: 12px;
  border-top: 1px solid var(--background-modifier-border);
}

.dmt-dungeon-subsection {
  font-size: 0.8em;
  font-weight: 500;
  color: var(--text-muted);
  margin-top: 8px;
  padding-left: 4px;
}

.dmt-checkbox-hint {
  font-size: 0.8em;
  color: var(--text-muted);
  margin-left: 142px;
  margin-top: 2px;
}

/* ===========================================
 * Object Sets
 * =========================================== */
.dmt-set-separator {
  border-top: 1px solid var(--background-modifier-border);
  margin: 1.5em 0 1em 0;
}

.dmt-set-active-bar {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  background: var(--background-secondary);
  border: 1px solid var(--interactive-accent);
  border-radius: 6px;
  margin-bottom: 12px;
  font-size: 13px;
}

.dmt-set-active-name {
  font-weight: 600;
  color: var(--interactive-accent);
}

.dmt-set-active-bar .dmt-settings-icon-btn {
  margin-left: auto;
  font-size: 11px;
}

.dmt-set-list {
  display: flex;
  flex-direction: column;
  gap: 4px;
  margin-bottom: 12px;
}

.dmt-set-row {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 10px;
  border-radius: 4px;
  background: var(--background-secondary);
  border: 1px solid transparent;
}

.dmt-set-row-active {
  border-color: var(--interactive-accent);
}

.dmt-set-name {
  font-weight: 500;
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.dmt-set-badges {
  display: flex;
  gap: 4px;
  flex-shrink: 0;
}

.dmt-set-badge {
  font-size: 10px;
  padding: 1px 6px;
  border-radius: 3px;
  background: var(--background-modifier-border);
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.dmt-set-badge-source {
  background: var(--background-modifier-border-hover, var(--background-modifier-border));
  font-style: italic;
}

.dmt-set-actions {
  display: flex;
  gap: 2px;
  flex-shrink: 0;
}

.dmt-set-modified-badge {
  color: var(--text-warning);
  font-size: 12px;
  font-style: italic;
}

.dmt-set-modified-bar {
  border-color: var(--text-warning);
}

/* ===========================================
 * Animations
 * =========================================== */
@keyframes dmt-shake {
  0%, 100% { transform: translateX(0); }
  25% { transform: translateX(-4px); }
  75% { transform: translateX(4px); }
}

.dmt-shake {
  animation: dmt-shake 0.3s ease;
}`;