/**
 * partyNoteOperations.ts
 *
 * Generates and maintains a party pin's vault note: a markdown table of the
 * pin's in-range results, updated by the same recalculation pipeline that
 * feeds the canvas overlay.
 *
 * Safety rules:
 * - Every generated note carries a frontmatter marker with the owning pin's
 *   id. Updates and deletions verify the marker first — a user note that
 *   happens to share the path is never overwritten or trashed.
 * - Writes are change-detected: identical content is never rewritten, so
 *   file modification times (and sync) stay quiet while nothing changes.
 * - A manually deleted note is recreated on the next update.
 */

import type { App } from 'obsidian';
import type { PartyPin } from '#types/core/map.types';
import type { PartyRangeResults } from '../objects/partyRangeQuery';

import { normalizePath, TFile as ObsidianTFile } from 'obsidian';
import { generateDeepLink } from './deepLinkHandler';

/** Frontmatter key marking a note as generated by a party pin */
const PARTY_NOTE_MARKER_KEY = 'windrose-party-pin';

/** Deeplink zoom used in note rows — fixed so content never churns with the viewport */
const NOTE_DEEP_LINK_ZOOM = 1.175;

/** Context about the map hosting the pin, for headings and deeplinks */
export interface PartyNoteContext {
  mapId: string;
  mapName: string;
  /** Path of the note hosting the map; '' when the map lives in a full-pane view */
  mapNotePath: string;
}

/** Outcome of an upsert, for caller feedback */
export type PartyNoteWriteResult = 'created' | 'updated' | 'unchanged' | 'blocked';

/** Outcome of a delete request */
export type PartyNoteDeleteResult = 'deleted' | 'not-found' | 'not-owned';

/**
 * Make a label safe to use as a note file name.
 * Falls back to 'Party' when nothing survives.
 */
function sanitizePartyNoteFileName(label: string): string {
  const cleaned = label
    .replace(/[\\/:*?"<>|#^[\]]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  return cleaned === '' ? 'Party' : cleaned;
}

/**
 * Build the full vault path for a pin's note in the given folder.
 * @param folder - Vault folder ('' for the vault root)
 */
function buildPartyNotePath(folder: string, label: string): string {
  const fileName = `${sanitizePartyNoteFileName(label)} - Nearby.md`;
  const trimmed = folder.trim().replace(/^\/+|\/+$/g, '');
  return normalizePath(trimmed === '' ? fileName : `${trimmed}/${fileName}`);
}

/** Escape a string for use inside a markdown table cell */
function escapeTableCell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

/**
 * Render the note's full markdown content for the current results.
 * Pure — content equality doubles as the change detector.
 */
function buildPartyNoteContent(
  pin: PartyPin,
  results: PartyRangeResults,
  context: PartyNoteContext
): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push(`${PARTY_NOTE_MARKER_KEY}: ${pin.id}`);
  lines.push('---');
  lines.push('');
  lines.push(`# ${pin.label} - Nearby`);
  lines.push('');
  lines.push(`Within **${pin.range}** of the party on **${context.mapName}**.`);
  lines.push('');

  if (results.linked.length === 0 && results.unlinked.length === 0) {
    lines.push('*Nothing in range.*');
    lines.push('');
    return lines.join('\n');
  }

  if (results.linked.length > 0) {
    const hasDeepLinks = context.mapNotePath !== '';
    lines.push(hasDeepLinks ? '| Note | Distance | Map |' : '| Note | Distance |');
    lines.push(hasDeepLinks ? '| --- | --- | --- |' : '| --- | --- |');
    for (const result of results.linked) {
      const linkTarget = result.notePath.replace(/\.md$/, '');
      const link = `[[${escapeTableCell(linkTarget)}\\|${escapeTableCell(result.displayName)}]]`;
      const distance = escapeTableCell(result.distanceLabel);
      if (hasDeepLinks) {
        const url = generateDeepLink(
          context.mapNotePath, context.mapId,
          result.position.x, result.position.y,
          NOTE_DEEP_LINK_ZOOM, ''
        );
        lines.push(`| ${link} | ${distance} | [show](${url}) |`);
      } else {
        lines.push(`| ${link} | ${distance} |`);
      }
    }
    lines.push('');
  }

  if (results.unlinked.length > 0) {
    lines.push('## Unlinked');
    lines.push('');
    lines.push('| Marker | Distance |');
    lines.push('| --- | --- |');
    for (const result of results.unlinked) {
      lines.push(`| ${escapeTableCell(result.label)} | ${escapeTableCell(result.distanceLabel)} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Check whether note content carries this pin's ownership marker.
 * Reads the raw frontmatter block directly (deterministic — no dependency
 * on metadata cache freshness at decision time).
 */
function isOwnedPartyNoteContent(content: string, pinId: string): boolean {
  const frontmatter = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!frontmatter) return false;
  const markerLine = new RegExp(`^${PARTY_NOTE_MARKER_KEY}:\\s*(.+)$`, 'm').exec(frontmatter[1]);
  return markerLine != null && markerLine[1].trim() === pinId;
}

/** Ensure the folder chain for a note path exists */
async function ensureParentFolder(app: App, notePath: string): Promise<void> {
  const lastSlash = notePath.lastIndexOf('/');
  if (lastSlash === -1) return;
  const folder = notePath.slice(0, lastSlash);
  if (app.vault.getAbstractFileByPath(folder) != null) return;
  await app.vault.createFolder(folder).catch(() => {
    // Folder may have been created concurrently; the create call below
    // surfaces any real failure
  });
}

/**
 * Create or update the pin's note with the given content.
 * - Missing file (including manual deletion): recreated
 * - Existing file without this pin's marker: left untouched ('blocked')
 * - Identical content: no write ('unchanged')
 */
async function upsertPartyNote(app: App, pin: PartyPin, content: string): Promise<PartyNoteWriteResult> {
  const path = pin.partyNote?.path;
  if (path == null || path === '') return 'blocked';

  const existing = app.vault.getAbstractFileByPath(path);
  if (existing == null) {
    await ensureParentFolder(app, path);
    await app.vault.create(path, content);
    return 'created';
  }
  if (!(existing instanceof ObsidianTFile)) return 'blocked';

  const currentContent = await app.vault.read(existing);
  if (!isOwnedPartyNoteContent(currentContent, pin.id)) return 'blocked';
  if (currentContent === content) return 'unchanged';

  await app.vault.modify(existing, content);
  return 'updated';
}

/**
 * Trash the pin's note after verifying this pin generated it.
 * Uses fileManager.trashFile so the user's trash preference is honored.
 */
async function deletePartyNote(app: App, pin: PartyPin): Promise<PartyNoteDeleteResult> {
  const path = pin.partyNote?.path;
  if (path == null || path === '') return 'not-found';

  const existing = app.vault.getAbstractFileByPath(path);
  if (existing == null || !(existing instanceof ObsidianTFile)) return 'not-found';

  const content = await app.vault.read(existing);
  if (!isOwnedPartyNoteContent(content, pin.id)) return 'not-owned';

  await app.fileManager.trashFile(existing);
  return 'deleted';
}

export {
  PARTY_NOTE_MARKER_KEY,
  sanitizePartyNoteFileName,
  buildPartyNotePath,
  buildPartyNoteContent,
  isOwnedPartyNoteContent,
  upsertPartyNote,
  deletePartyNote,
};
