/**
 * rpgAwesomeIcons.ts - Icon mapping and categories for RPGAwesome font
 * Generated from official rpg-awesome npm package v0.2.0
 * Source: scss/_variables.scss
 * License: SIL OFL 1.1 (Font), MIT (CSS)
 * Total icons: 496
 */

import type { IconCategory, IconData, IconMap, IconWithClass } from '#types/objects/icon.types';

/**
 * Icon categories for filtering in the picker UI
 */
const RA_CATEGORIES: IconCategory[] = [
  { id: 'weapons', label: 'Weapons', order: 10 },
  { id: 'armor', label: 'Armor & Defense', order: 20 },
  { id: 'creatures', label: 'Creatures', order: 30 },
  { id: 'potions', label: 'Potions', order: 40 },
  { id: 'magic', label: 'Magic', order: 50 },
  { id: 'food', label: 'Food & Drink', order: 60 },
  { id: 'plants', label: 'Plants', order: 70 },
  { id: 'astrology', label: 'Astrology', order: 80 },
  { id: 'cards-dice', label: 'Cards & Dice', order: 90 },
  { id: 'electronics', label: 'Electronics', order: 100 },
  { id: 'dangers', label: 'Dangers', order: 110 },
  { id: 'player', label: 'Player', order: 120 },
  { id: 'inventory', label: 'Inventory', order: 130 },
  { id: 'rpg', label: 'RPG & Misc', order: 140 },
];

/**
 * Icon definitions - char is the actual Unicode character for canvas rendering
 * Codepoints are from the official _variables.scss file
 */
const RA_ICONS: IconMap = {
  'ra-acid': { char: '\ue900', label: 'Acid', category: 'dangers' },
  'ra-acorn': { char: '\ue901', label: 'Acorn', category: 'food' },
  'ra-alien-fire': { char: '\ue902', label: 'Alien Fire', category: 'magic' },
  'ra-all-for-one': { char: '\ue903', label: 'All For One', category: 'rpg' },
  'ra-alligator-clip': { char: '\ue904', label: 'Alligator Clip', category: 'inventory' },
  'ra-ammo-bag': { char: '\ue905', label: 'Ammo Bag', category: 'inventory' },
  'ra-anchor': { char: '\ue906', label: 'Anchor', category: 'rpg' },
  'ra-angel-wings': { char: '\ue907', label: 'Angel Wings', category: 'rpg' },
  'ra-ankh': { char: '\ue908', label: 'Ankh', category: 'rpg' },
  'ra-anvil': { char: '\ue909', label: 'Anvil', category: 'rpg' },
  'ra-apple': { char: '\ue90a', label: 'Apple', category: 'food' },
  'ra-aquarius': { char: '\ue90b', label: 'Aquarius', category: 'astrology' },
  'ra-arcane-mask': { char: '\ue90c', label: 'Arcane Mask', category: 'armor' },
  'ra-archer': { char: '\ue90d', label: 'Archer', category: 'weapons' },
  'ra-archery-target': { char: '\ue90e', label: 'Archery Target', category: 'weapons' },
  'ra-arena': { char: '\ue90f', label: 'Arena', category: 'rpg' },
  'ra-aries': { char: '\ue910', label: 'Aries', category: 'astrology' },
  'ra-arrow-cluster': { char: '\ue911', label: 'Arrow Cluster', category: 'weapons' },
  'ra-arrow-flights': { char: '\ue912', label: 'Arrow Flights', category: 'weapons' },
  'ra-arson': { char: '\ue913', label: 'Arson', category: 'dangers' },
  'ra-aura': { char: '\ue914', label: 'Aura', category: 'magic' },
  'ra-aware': { char: '\ue915', label: 'Aware', category: 'player' },
  'ra-axe': { char: '\ue917', label: 'Axe', category: 'weapons' },
  'ra-axe-swing': { char: '\ue916', label: 'Axe Swing', category: 'weapons' },
  'ra-ball': { char: '\ue918', label: 'Ball', category: 'inventory' },
  'ra-barbed-arrow': { char: '\ue919', label: 'Barbed Arrow', category: 'weapons' },
  'ra-barrier': { char: '\ue91a', label: 'Barrier', category: 'armor' },
  'ra-bat-sword': { char: '\ue91b', label: 'Bat Sword', category: 'weapons' },
  'ra-battered-axe': { char: '\ue91c', label: 'Battered Axe', category: 'weapons' },
  'ra-batteries': { char: '\ue91d', label: 'Batteries', category: 'electronics' },
  'ra-battery-0': { char: '\ue91e', label: 'Battery 0', category: 'electronics' },
  'ra-battery-100': { char: '\ue922', label: 'Battery 100', category: 'electronics' },
  'ra-battery-25': { char: '\ue91f', label: 'Battery 25', category: 'electronics' },
  'ra-battery-50': { char: '\ue920', label: 'Battery 50', category: 'electronics' },
  'ra-battery-75': { char: '\ue921', label: 'Battery 75', category: 'electronics' },
  'ra-battery-black': { char: '\ue923', label: 'Battery Black', category: 'electronics' },
  'ra-battery-negative': { char: '\ue924', label: 'Battery Negative', category: 'electronics' },
  'ra-battery-positive': { char: '\ue925', label: 'Battery Positive', category: 'electronics' },
  'ra-battery-white': { char: '\ue926', label: 'Battery White', category: 'electronics' },
  'ra-batwings': { char: '\ue927', label: 'Batwings', category: 'rpg' },
  'ra-beam-wake': { char: '\ue928', label: 'Beam Wake', category: 'rpg' },
  'ra-bear-trap': { char: '\ue929', label: 'Bear Trap', category: 'dangers' },
  'ra-beer': { char: '\ue92a', label: 'Beer', category: 'food' },
  'ra-beetle': { char: '\ue92b', label: 'Beetle', category: 'creatures' },
  'ra-bell': { char: '\ue92c', label: 'Bell', category: 'inventory' },
  'ra-biohazard': { char: '\ue92d', label: 'Biohazard', category: 'dangers' },
  'ra-bird-claw': { char: '\ue92e', label: 'Bird Claw', category: 'creatures' },
  'ra-bird-mask': { char: '\ue92f', label: 'Bird Mask', category: 'armor' },
  'ra-blade-bite': { char: '\ue930', label: 'Blade Bite', category: 'dangers' },
  'ra-blast': { char: '\ue931', label: 'Blast', category: 'dangers' },
  'ra-blaster': { char: '\ue932', label: 'Blaster', category: 'weapons' },
  'ra-bleeding-eye': { char: '\ue933', label: 'Bleeding Eye', category: 'dangers' },
  'ra-bleeding-hearts': { char: '\ue934', label: 'Bleeding Hearts', category: 'dangers' },
  'ra-bolt-shield': { char: '\ue935', label: 'Bolt Shield', category: 'armor' },
  'ra-bomb-explosion': { char: '\ue936', label: 'Bomb Explosion', category: 'dangers' },
  'ra-bombs': { char: '\ue937', label: 'Bombs', category: 'weapons' },
  'ra-bone-bite': { char: '\ue938', label: 'Bone Bite', category: 'dangers' },
  'ra-bone-knife': { char: '\ue939', label: 'Bone Knife', category: 'weapons' },
  'ra-book': { char: '\ue93a', label: 'Book', category: 'inventory' },
  'ra-boomerang': { char: '\ue93b', label: 'Boomerang', category: 'weapons' },
  'ra-boot-stomp': { char: '\ue93c', label: 'Boot Stomp', category: 'armor' },
  'ra-bottle-vapors': { char: '\ue93d', label: 'Bottle Vapors', category: 'potions' },
  'ra-bottled-bolt': { char: '\ue93e', label: 'Bottled Bolt', category: 'potions' },
  'ra-bottom-right': { char: '\ue93f', label: 'Bottom Right', category: 'cards-dice' },
  'ra-bowie-knife': { char: '\ue940', label: 'Bowie Knife', category: 'weapons' },
  'ra-bowling-pin': { char: '\ue941', label: 'Bowling Pin', category: 'inventory' },
  'ra-brain-freeze': { char: '\ue942', label: 'Brain Freeze', category: 'magic' },
  'ra-brandy-bottle': { char: '\ue943', label: 'Brandy Bottle', category: 'food' },
  'ra-bridge': { char: '\ue944', label: 'Bridge', category: 'rpg' },
  'ra-broadhead-arrow': { char: '\ue945', label: 'Broadhead Arrow', category: 'weapons' },
  'ra-broadsword': { char: '\ue946', label: 'Broadsword', category: 'weapons' },
  'ra-broken-bone': { char: '\ue947', label: 'Broken Bone', category: 'dangers' },
  'ra-broken-bottle': { char: '\ue948', label: 'Broken Bottle', category: 'potions' },
  'ra-broken-heart': { char: '\ue949', label: 'Broken Heart', category: 'dangers' },
  'ra-broken-shield': { char: '\ue94a', label: 'Broken Shield', category: 'armor' },
  'ra-broken-skull': { char: '\ue94b', label: 'Broken Skull', category: 'dangers' },
  'ra-bubbling-potion': { char: '\ue94c', label: 'Bubbling Potion', category: 'potions' },
  'ra-bullets': { char: '\ue94d', label: 'Bullets', category: 'weapons' },
  'ra-burning-book': { char: '\ue94e', label: 'Burning Book', category: 'magic' },
  'ra-burning-embers': { char: '\ue94f', label: 'Burning Embers', category: 'magic' },
  'ra-burning-eye': { char: '\ue950', label: 'Burning Eye', category: 'magic' },
  'ra-burning-meteor': { char: '\ue951', label: 'Burning Meteor', category: 'magic' },
  'ra-burst-blob': { char: '\ue952', label: 'Burst Blob', category: 'magic' },
  'ra-butterfly': { char: '\ue953', label: 'Butterfly', category: 'creatures' },
  'ra-campfire': { char: '\ue954', label: 'Campfire', category: 'rpg' },
  'ra-cancel': { char: '\ue955', label: 'Cancel', category: 'cards-dice' },
  'ra-cancer': { char: '\ue956', label: 'Cancer', category: 'astrology' },
  'ra-candle': { char: '\ue958', label: 'Candle', category: 'inventory' },
  'ra-candle-fire': { char: '\ue957', label: 'Candle Fire', category: 'inventory' },
  'ra-cannon-shot': { char: '\ue959', label: 'Cannon Shot', category: 'weapons' },
  'ra-capitol': { char: '\ue95a', label: 'Capitol', category: 'rpg' },
  'ra-capricorn': { char: '\ue95b', label: 'Capricorn', category: 'astrology' },
  'ra-carrot': { char: '\ue95c', label: 'Carrot', category: 'food' },
  'ra-castle-emblem': { char: '\ue95d', label: 'Castle Emblem', category: 'rpg' },
  'ra-castle-flag': { char: '\ue95e', label: 'Castle Flag', category: 'inventory' },
  'ra-cat': { char: '\ue95f', label: 'Cat', category: 'creatures' },
  'ra-chain': { char: '\ue960', label: 'Chain', category: 'inventory' },
  'ra-cheese': { char: '\ue961', label: 'Cheese', category: 'food' },
  'ra-chemical-arrow': { char: '\ue962', label: 'Chemical Arrow', category: 'weapons' },
  'ra-chessboard': { char: '\ue963', label: 'Chessboard', category: 'cards-dice' },
  'ra-chicken-leg': { char: '\ue964', label: 'Chicken Leg', category: 'food' },
  'ra-circle-of-circles': { char: '\ue965', label: 'Circle Of Circles', category: 'rpg' },
  'ra-circular-saw': { char: '\ue966', label: 'Circular Saw', category: 'weapons' },
  'ra-circular-shield': { char: '\ue967', label: 'Circular Shield', category: 'armor' },
  'ra-cloak-and-dagger': { char: '\ue968', label: 'Cloak And Dagger', category: 'weapons' },
  'ra-clockwork': { char: '\ue969', label: 'Clockwork', category: 'electronics' },
  'ra-clover': { char: '\ue96a', label: 'Clover', category: 'plants' },
  'ra-clovers': { char: '\ue96c', label: 'Clovers', category: 'cards-dice' },
  'ra-clovers-card': { char: '\ue96b', label: 'Clovers Card', category: 'cards-dice' },
  'ra-cluster-bomb': { char: '\ue96d', label: 'Cluster Bomb', category: 'weapons' },
  'ra-coffee-mug': { char: '\ue96e', label: 'Coffee Mug', category: 'food' },
  'ra-cog': { char: '\ue970', label: 'Cog', category: 'electronics' },
  'ra-cog-wheel': { char: '\ue96f', label: 'Cog Wheel', category: 'electronics' },
  'ra-cold-heart': { char: '\ue971', label: 'Cold Heart', category: 'magic' },
  'ra-compass': { char: '\ue972', label: 'Compass', category: 'inventory' },
  'ra-corked-tube': { char: '\ue973', label: 'Corked Tube', category: 'potions' },
  'ra-crab-claw': { char: '\ue974', label: 'Crab Claw', category: 'creatures' },
  'ra-cracked-helm': { char: '\ue975', label: 'Cracked Helm', category: 'armor' },
  'ra-cracked-shield': { char: '\ue976', label: 'Cracked Shield', category: 'armor' },
  'ra-croc-sword': { char: '\ue977', label: 'Croc Sword', category: 'weapons' },
  'ra-crossbow': { char: '\ue978', label: 'Crossbow', category: 'weapons' },
  'ra-crossed-axes': { char: '\ue979', label: 'Crossed Axes', category: 'weapons' },
  'ra-crossed-bones': { char: '\ue97a', label: 'Crossed Bones', category: 'dangers' },
  'ra-crossed-pistols': { char: '\ue97b', label: 'Crossed Pistols', category: 'weapons' },
  'ra-crossed-sabres': { char: '\ue97c', label: 'Crossed Sabres', category: 'weapons' },
  'ra-crossed-swords': { char: '\ue97d', label: 'Crossed Swords', category: 'weapons' },
  'ra-crown': { char: '\ue97f', label: 'Crown', category: 'armor' },
  'ra-crown-of-thorns': { char: '\ue97e', label: 'Crown Of Thorns', category: 'armor' },
  'ra-crowned-heart': { char: '\ue980', label: 'Crowned Heart', category: 'player' },
  'ra-crush': { char: '\ue981', label: 'Crush', category: 'dangers' },
  'ra-crystal-ball': { char: '\ue982', label: 'Crystal Ball', category: 'magic' },
  'ra-crystal-cluster': { char: '\ue983', label: 'Crystal Cluster', category: 'magic' },
  'ra-crystal-wand': { char: '\ue984', label: 'Crystal Wand', category: 'magic' },
  'ra-crystals': { char: '\ue985', label: 'Crystals', category: 'magic' },
  'ra-cubes': { char: '\ue986', label: 'Cubes', category: 'rpg' },
  'ra-cut-palm': { char: '\ue987', label: 'Cut Palm', category: 'player' },
  'ra-cycle': { char: '\ue988', label: 'Cycle', category: 'rpg' },
  'ra-daggers': { char: '\ue989', label: 'Daggers', category: 'weapons' },
  'ra-daisy': { char: '\ue98a', label: 'Daisy', category: 'plants' },
  'ra-dead-tree': { char: '\ue98b', label: 'Dead Tree', category: 'plants' },
  'ra-death-skull': { char: '\ue98c', label: 'Death Skull', category: 'dangers' },
  'ra-decapitation': { char: '\ue98d', label: 'Decapitation', category: 'dangers' },
  'ra-defibrillate': { char: '\ue98e', label: 'Defibrillate', category: 'electronics' },
  'ra-demolish': { char: '\ue98f', label: 'Demolish', category: 'dangers' },
  'ra-dervish-swords': { char: '\ue990', label: 'Dervish Swords', category: 'weapons' },
  'ra-desert-skull': { char: '\ue991', label: 'Desert Skull', category: 'dangers' },
  'ra-diamond': { char: '\ue992', label: 'Diamond', category: 'magic' },
  'ra-diamonds': { char: '\ue994', label: 'Diamonds', category: 'cards-dice' },
  'ra-diamonds-card': { char: '\ue993', label: 'Diamonds Card', category: 'cards-dice' },
  'ra-dice-five': { char: '\ue995', label: 'Dice Five', category: 'cards-dice' },
  'ra-dice-four': { char: '\ue996', label: 'Dice Four', category: 'cards-dice' },
  'ra-dice-one': { char: '\ue997', label: 'Dice One', category: 'cards-dice' },
  'ra-dice-six': { char: '\ue998', label: 'Dice Six', category: 'cards-dice' },
  'ra-dice-three': { char: '\ue999', label: 'Dice Three', category: 'cards-dice' },
  'ra-dice-two': { char: '\ue99a', label: 'Dice Two', category: 'cards-dice' },
  'ra-dinosaur': { char: '\ue99b', label: 'Dinosaur', category: 'creatures' },
  'ra-divert': { char: '\ue99c', label: 'Divert', category: 'magic' },
  'ra-diving-dagger': { char: '\ue99d', label: 'Diving Dagger', category: 'weapons' },
  'ra-double-team': { char: '\ue99e', label: 'Double Team', category: 'player' },
  'ra-doubled': { char: '\ue99f', label: 'Doubled', category: 'magic' },
  'ra-dragon': { char: '\ue9a2', label: 'Dragon', category: 'creatures' },
  'ra-dragon-breath': { char: '\ue9a0', label: 'Dragon Breath', category: 'magic' },
  'ra-dragon-wing': { char: '\ue9a1', label: 'Dragon Wing', category: 'creatures' },
  'ra-dragonfly': { char: '\ue9a3', label: 'Dragonfly', category: 'creatures' },
  'ra-drill': { char: '\ue9a4', label: 'Drill', category: 'weapons' },
  'ra-dripping-blade': { char: '\ue9a5', label: 'Dripping Blade', category: 'weapons' },
  'ra-dripping-knife': { char: '\ue9a6', label: 'Dripping Knife', category: 'weapons' },
  'ra-dripping-sword': { char: '\ue9a7', label: 'Dripping Sword', category: 'weapons' },
  'ra-droplet': { char: '\ue9a9', label: 'Droplet', category: 'magic' },
  'ra-droplet-splash': { char: '\ue9a8', label: 'Droplet Splash', category: 'magic' },
  'ra-droplets': { char: '\ue9aa', label: 'Droplets', category: 'rpg' },
  'ra-duel': { char: '\ue9ab', label: 'Duel', category: 'weapons' },
  'ra-egg': { char: '\ue9ad', label: 'Egg', category: 'food' },
  'ra-egg-pod': { char: '\ue9ac', label: 'Egg Pod', category: 'food' },
  'ra-eggplant': { char: '\ue9ae', label: 'Eggplant', category: 'food' },
  'ra-emerald': { char: '\ue9af', label: 'Emerald', category: 'magic' },
  'ra-energise': { char: '\ue9b0', label: 'Energise', category: 'electronics' },
  'ra-explosion': { char: '\ue9b1', label: 'Explosion', category: 'dangers' },
  'ra-explosive-materials': { char: '\ue9b2', label: 'Explosive Materials', category: 'weapons' },
  'ra-eye-monster': { char: '\ue9b3', label: 'Eye Monster', category: 'creatures' },
  'ra-eye-shield': { char: '\ue9b4', label: 'Eye Shield', category: 'armor' },
  'ra-eyeball': { char: '\ue9b5', label: 'Eyeball', category: 'magic' },
  'ra-fairy': { char: '\ue9b7', label: 'Fairy', category: 'creatures' },
  'ra-fairy-wand': { char: '\ue9b6', label: 'Fairy Wand', category: 'magic' },
  'ra-fall-down': { char: '\ue9b8', label: 'Fall Down', category: 'dangers' },
  'ra-falling': { char: '\ue9b9', label: 'Falling', category: 'player' },
  'ra-fast-ship': { char: '\ue9ba', label: 'Fast Ship', category: 'electronics' },
  'ra-feather-wing': { char: '\ue9bb', label: 'Feather Wing', category: 'rpg' },
  'ra-feathered-wing': { char: '\ue9bc', label: 'Feathered Wing', category: 'rpg' },
  'ra-fedora': { char: '\ue9bd', label: 'Fedora', category: 'armor' },
  'ra-fire': { char: '\ue9c3', label: 'Fire', category: 'magic' },
  'ra-fire-bomb': { char: '\ue9be', label: 'Fire Bomb', category: 'weapons' },
  'ra-fire-breath': { char: '\ue9bf', label: 'Fire Breath', category: 'magic' },
  'ra-fire-ring': { char: '\ue9c0', label: 'Fire Ring', category: 'magic' },
  'ra-fire-shield': { char: '\ue9c1', label: 'Fire Shield', category: 'armor' },
  'ra-fire-symbol': { char: '\ue9c2', label: 'Fire Symbol', category: 'magic' },
  'ra-fireball-sword': { char: '\ue9c4', label: 'Fireball Sword', category: 'weapons' },
  'ra-fish': { char: '\ue9c5', label: 'Fish', category: 'creatures' },
  'ra-fizzing-flask': { char: '\ue9c6', label: 'Fizzing Flask', category: 'potions' },
  'ra-flame-symbol': { char: '\ue9c7', label: 'Flame Symbol', category: 'magic' },
  'ra-flaming-arrow': { char: '\ue9c8', label: 'Flaming Arrow', category: 'weapons' },
  'ra-flaming-claw': { char: '\ue9c9', label: 'Flaming Claw', category: 'weapons' },
  'ra-flaming-trident': { char: '\ue9ca', label: 'Flaming Trident', category: 'weapons' },
  'ra-flask': { char: '\ue9cb', label: 'Flask', category: 'potions' },
  'ra-flat-hammer': { char: '\ue9cc', label: 'Flat Hammer', category: 'weapons' },
  'ra-flower': { char: '\ue9cd', label: 'Flower', category: 'plants' },
  'ra-flowers': { char: '\ue9ce', label: 'Flowers', category: 'plants' },
  'ra-fluffy-swirl': { char: '\ue9cf', label: 'Fluffy Swirl', category: 'rpg' },
  'ra-focused-lightning': { char: '\ue9d0', label: 'Focused Lightning', category: 'magic' },
  'ra-food-chain': { char: '\ue9d1', label: 'Food Chain', category: 'dangers' },
  'ra-footprint': { char: '\ue9d2', label: 'Footprint', category: 'player' },
  'ra-forging': { char: '\ue9d3', label: 'Forging', category: 'rpg' },
  'ra-forward': { char: '\ue9d4', label: 'Forward', category: 'rpg' },
  'ra-fox': { char: '\ue9d5', label: 'Fox', category: 'creatures' },
  'ra-frost-emblem': { char: '\ue9d6', label: 'Frost Emblem', category: 'magic' },
  'ra-frostfire': { char: '\ue9d7', label: 'Frostfire', category: 'magic' },
  'ra-frozen-arrow': { char: '\ue9d8', label: 'Frozen Arrow', category: 'weapons' },
  'ra-gamepad-cross': { char: '\ue9d9', label: 'Gamepad Cross', category: 'electronics' },
  'ra-gavel': { char: '\ue9da', label: 'Gavel', category: 'weapons' },
  'ra-gear-hammer': { char: '\ue9db', label: 'Gear Hammer', category: 'weapons' },
  'ra-gear-heart': { char: '\ue9dc', label: 'Gear Heart', category: 'electronics' },
  'ra-gears': { char: '\ue9dd', label: 'Gears', category: 'electronics' },
  'ra-gecko': { char: '\ue9de', label: 'Gecko', category: 'creatures' },
  'ra-gem': { char: '\ue9e0', label: 'Gem', category: 'magic' },
  'ra-gem-pendant': { char: '\ue9df', label: 'Gem Pendant', category: 'magic' },
  'ra-gemini': { char: '\ue9e1', label: 'Gemini', category: 'astrology' },
  'ra-glass-heart': { char: '\ue9e2', label: 'Glass Heart', category: 'player' },
  'ra-gloop': { char: '\ue9e3', label: 'Gloop', category: 'magic' },
  'ra-gold-bar': { char: '\ue9e4', label: 'Gold Bar', category: 'magic' },
  'ra-grappling-hook': { char: '\ue9e5', label: 'Grappling Hook', category: 'weapons' },
  'ra-grass': { char: '\ue9e7', label: 'Grass', category: 'plants' },
  'ra-grass-patch': { char: '\ue9e6', label: 'Grass Patch', category: 'plants' },
  'ra-grenade': { char: '\ue9e8', label: 'Grenade', category: 'weapons' },
  'ra-groundbreaker': { char: '\ue9e9', label: 'Groundbreaker', category: 'rpg' },
  'ra-guarded-tower': { char: '\ue9ea', label: 'Guarded Tower', category: 'rpg' },
  'ra-guillotine': { char: '\ue9eb', label: 'Guillotine', category: 'weapons' },
  'ra-halberd': { char: '\ue9ec', label: 'Halberd', category: 'weapons' },
  'ra-hammer': { char: '\ue9ee', label: 'Hammer', category: 'weapons' },
  'ra-hammer-drop': { char: '\ue9ed', label: 'Hammer Drop', category: 'weapons' },
  'ra-hand': { char: '\ue9f1', label: 'Hand', category: 'player' },
  'ra-hand-emblem': { char: '\ue9ef', label: 'Hand Emblem', category: 'player' },
  'ra-hand-saw': { char: '\ue9f0', label: 'Hand Saw', category: 'weapons' },
  'ra-harpoon-trident': { char: '\ue9f2', label: 'Harpoon Trident', category: 'weapons' },
  'ra-health': { char: '\ue9f5', label: 'Health', category: 'magic' },
  'ra-health-decrease': { char: '\ue9f3', label: 'Health Decrease', category: 'magic' },
  'ra-health-increase': { char: '\ue9f4', label: 'Health Increase', category: 'magic' },
  'ra-heart-bottle': { char: '\ue9f6', label: 'Heart Bottle', category: 'potions' },
  'ra-heart-tower': { char: '\ue9f7', label: 'Heart Tower', category: 'rpg' },
  'ra-heartburn': { char: '\ue9f8', label: 'Heartburn', category: 'dangers' },
  'ra-hearts': { char: '\ue9fa', label: 'Hearts', category: 'cards-dice' },
  'ra-hearts-card': { char: '\ue9f9', label: 'Hearts Card', category: 'cards-dice' },
  'ra-heat-haze': { char: '\ue9fb', label: 'Heat Haze', category: 'rpg' },
  'ra-heavy-fall': { char: '\ue9fc', label: 'Heavy Fall', category: 'dangers' },
  'ra-heavy-shield': { char: '\ue9fd', label: 'Heavy Shield', category: 'armor' },
  'ra-helmet': { char: '\ue9fe', label: 'Helmet', category: 'armor' },
  'ra-help': { char: '\ue9ff', label: 'Help', category: 'rpg' },
  'ra-hive-emblem': { char: '\uea00', label: 'Hive Emblem', category: 'rpg' },
  'ra-hole-ladder': { char: '\uea01', label: 'Hole Ladder', category: 'rpg' },
  'ra-honeycomb': { char: '\uea02', label: 'Honeycomb', category: 'food' },
  'ra-hood': { char: '\uea03', label: 'Hood', category: 'armor' },
  'ra-horn-call': { char: '\uea04', label: 'Horn Call', category: 'rpg' },
  'ra-horns': { char: '\uea05', label: 'Horns', category: 'rpg' },
  'ra-horseshoe': { char: '\uea06', label: 'Horseshoe', category: 'inventory' },
  'ra-hospital-cross': { char: '\uea07', label: 'Hospital Cross', category: 'magic' },
  'ra-hot-surface': { char: '\uea08', label: 'Hot Surface', category: 'magic' },
  'ra-hourglass': { char: '\uea09', label: 'Hourglass', category: 'inventory' },
  'ra-hydra': { char: '\uea0b', label: 'Hydra', category: 'creatures' },
  'ra-hydra-shot': { char: '\uea0a', label: 'Hydra Shot', category: 'magic' },
  'ra-ice-cube': { char: '\uea0c', label: 'Ice Cube', category: 'food' },
  'ra-implosion': { char: '\uea0d', label: 'Implosion', category: 'dangers' },
  'ra-incense': { char: '\uea0e', label: 'Incense', category: 'magic' },
  'ra-insect-jaws': { char: '\uea0f', label: 'Insect Jaws', category: 'creatures' },
  'ra-interdiction': { char: '\uea10', label: 'Interdiction', category: 'rpg' },
  'ra-jetpack': { char: '\uea11', label: 'Jetpack', category: 'electronics' },
  'ra-jigsaw-piece': { char: '\uea12', label: 'Jigsaw Piece', category: 'inventory' },
  'ra-kaleidoscope': { char: '\uea13', label: 'Kaleidoscope', category: 'magic' },
  'ra-kettlebell': { char: '\uea14', label: 'Kettlebell', category: 'inventory' },
  'ra-key': { char: '\uea16', label: 'Key', category: 'inventory' },
  'ra-key-basic': { char: '\uea15', label: 'Key Basic', category: 'inventory' },
  'ra-kitchen-knives': { char: '\uea17', label: 'Kitchen Knives', category: 'weapons' },
  'ra-knife': { char: '\uea19', label: 'Knife', category: 'weapons' },
  'ra-knife-fork': { char: '\uea18', label: 'Knife Fork', category: 'food' },
  'ra-knight-helmet': { char: '\uea1a', label: 'Knight Helmet', category: 'armor' },
  'ra-kunai': { char: '\uea1b', label: 'Kunai', category: 'weapons' },
  'ra-lantern-flame': { char: '\uea1c', label: 'Lantern Flame', category: 'inventory' },
  'ra-large-hammer': { char: '\uea1d', label: 'Large Hammer', category: 'weapons' },
  'ra-laser-blast': { char: '\uea1e', label: 'Laser Blast', category: 'weapons' },
  'ra-laser-site': { char: '\uea1f', label: 'Laser Site', category: 'electronics' },
  'ra-lava': { char: '\uea20', label: 'Lava', category: 'magic' },
  'ra-leaf': { char: '\uea21', label: 'Leaf', category: 'plants' },
  'ra-leo': { char: '\uea22', label: 'Leo', category: 'astrology' },
  'ra-level-four': { char: '\uea24', label: 'Level Four', category: 'magic' },
  'ra-level-four-advanced': { char: '\uea23', label: 'Level Four Advanced', category: 'magic' },
  'ra-level-three': { char: '\uea26', label: 'Level Three', category: 'magic' },
  'ra-level-three-advanced': { char: '\uea25', label: 'Level Three Advanced', category: 'magic' },
  'ra-level-two': { char: '\uea28', label: 'Level Two', category: 'magic' },
  'ra-level-two-advanced': { char: '\uea27', label: 'Level Two Advanced', category: 'magic' },
  'ra-lever': { char: '\uea29', label: 'Lever', category: 'electronics' },
  'ra-libra': { char: '\uea2a', label: 'Libra', category: 'astrology' },
  'ra-light-bulb': { char: '\uea2b', label: 'Light Bulb', category: 'electronics' },
  'ra-lighthouse': { char: '\uea2c', label: 'Lighthouse', category: 'electronics' },
  'ra-lightning': { char: '\uea31', label: 'Lightning', category: 'magic' },
  'ra-lightning-bolt': { char: '\uea2d', label: 'Lightning Bolt', category: 'magic' },
  'ra-lightning-storm': { char: '\uea2e', label: 'Lightning Storm', category: 'magic' },
  'ra-lightning-sword': { char: '\uea2f', label: 'Lightning Sword', category: 'weapons' },
  'ra-lightning-trio': { char: '\uea30', label: 'Lightning Trio', category: 'magic' },
  'ra-lion': { char: '\uea32', label: 'Lion', category: 'creatures' },
  'ra-lit-candelabra': { char: '\uea33', label: 'Lit Candelabra', category: 'inventory' },
  'ra-load': { char: '\uea34', label: 'Load', category: 'electronics' },
  'ra-locked-fortress': { char: '\uea35', label: 'Locked Fortress', category: 'rpg' },
  'ra-love-howl': { char: '\uea36', label: 'Love Howl', category: 'creatures' },
  'ra-maggot': { char: '\uea37', label: 'Maggot', category: 'creatures' },
  'ra-magnet': { char: '\uea38', label: 'Magnet', category: 'electronics' },
  'ra-mass-driver': { char: '\uea39', label: 'Mass Driver', category: 'weapons' },
  'ra-match': { char: '\uea3a', label: 'Match', category: 'inventory' },
  'ra-meat': { char: '\uea3c', label: 'Meat', category: 'food' },
  'ra-meat-hook': { char: '\uea3b', label: 'Meat Hook', category: 'weapons' },
  'ra-medical-pack': { char: '\uea3d', label: 'Medical Pack', category: 'inventory' },
  'ra-metal-gate': { char: '\uea3e', label: 'Metal Gate', category: 'rpg' },
  'ra-microphone': { char: '\uea3f', label: 'Microphone', category: 'electronics' },
  'ra-mine-wagon': { char: '\uea40', label: 'Mine Wagon', category: 'rpg' },
  'ra-mining-diamonds': { char: '\uea41', label: 'Mining Diamonds', category: 'magic' },
  'ra-mirror': { char: '\uea42', label: 'Mirror', category: 'inventory' },
  'ra-monster-skull': { char: '\uea43', label: 'Monster Skull', category: 'creatures' },
  'ra-moon-sun': { char: '\uea45', label: 'Moon Sun', category: 'astrology' },
  'ra-mountains': { char: '\uea44', label: 'Mountains', category: 'rpg' },
  'ra-mp5': { char: '\uea46', label: 'Mp5', category: 'weapons' },
  'ra-muscle-fat': { char: '\uea47', label: 'Muscle Fat', category: 'player' },
  'ra-muscle-up': { char: '\uea48', label: 'Muscle Up', category: 'player' },
  'ra-musket': { char: '\uea49', label: 'Musket', category: 'weapons' },
  'ra-nails': { char: '\uea4a', label: 'Nails', category: 'inventory' },
  'ra-nodular': { char: '\uea4b', label: 'Nodular', category: 'rpg' },
  'ra-noose': { char: '\uea4c', label: 'Noose', category: 'dangers' },
  'ra-nuclear': { char: '\uea4d', label: 'Nuclear', category: 'electronics' },
  'ra-ocarina': { char: '\uea4e', label: 'Ocarina', category: 'inventory' },
  'ra-ocean-emblem': { char: '\uea4f', label: 'Ocean Emblem', category: 'rpg' },
  'ra-octopus': { char: '\uea50', label: 'Octopus', category: 'creatures' },
  'ra-omega': { char: '\uea51', label: 'Omega', category: 'rpg' },
  'ra-on-target': { char: '\uea52', label: 'On Target', category: 'rpg' },
  'ra-ophiuchus': { char: '\uea53', label: 'Ophiuchus', category: 'astrology' },
  'ra-overhead': { char: '\uea54', label: 'Overhead', category: 'rpg' },
  'ra-overmind': { char: '\uea55', label: 'Overmind', category: 'rpg' },
  'ra-palm-tree': { char: '\uea56', label: 'Palm Tree', category: 'plants' },
  'ra-pawn': { char: '\uea57', label: 'Pawn', category: 'cards-dice' },
  'ra-pawprint': { char: '\uea58', label: 'Pawprint', category: 'player' },
  'ra-perspective-dice-five': { char: '\uea59', label: 'Perspective Dice Five', category: 'cards-dice' },
  'ra-perspective-dice-four': { char: '\uea5a', label: 'Perspective Dice Four', category: 'cards-dice' },
  'ra-perspective-dice-one': { char: '\uea5b', label: 'Perspective Dice One', category: 'cards-dice' },
  'ra-perspective-dice-random': { char: '\uea5c', label: 'Perspective Dice Random', category: 'cards-dice' },
  'ra-perspective-dice-six': { char: '\uea5e', label: 'Perspective Dice Six', category: 'cards-dice' },
  'ra-perspective-dice-three': { char: '\uea5f', label: 'Perspective Dice Three', category: 'cards-dice' },
  'ra-perspective-dice-two': { char: '\uea5d', label: 'Perspective Dice Two', category: 'cards-dice' },
  'ra-pill': { char: '\uea60', label: 'Pill', category: 'inventory' },
  'ra-pills': { char: '\uea61', label: 'Pills', category: 'inventory' },
  'ra-pine-tree': { char: '\uea62', label: 'Pine Tree', category: 'plants' },
  'ra-ping-pong': { char: '\uea63', label: 'Ping Pong', category: 'inventory' },
  'ra-pisces': { char: '\uea64', label: 'Pisces', category: 'astrology' },
  'ra-plain-dagger': { char: '\uea65', label: 'Plain Dagger', category: 'weapons' },
  'ra-player': { char: '\uea6f', label: 'Player', category: 'player' },
  'ra-player-despair': { char: '\uea66', label: 'Player Despair', category: 'player' },
  'ra-player-dodge': { char: '\uea67', label: 'Player Dodge', category: 'player' },
  'ra-player-king': { char: '\uea68', label: 'Player King', category: 'player' },
  'ra-player-lift': { char: '\uea69', label: 'Player Lift', category: 'player' },
  'ra-player-pain': { char: '\uea6a', label: 'Player Pain', category: 'player' },
  'ra-player-pyromaniac': { char: '\uea6b', label: 'Player Pyromaniac', category: 'player' },
  'ra-player-shot': { char: '\uea6c', label: 'Player Shot', category: 'player' },
  'ra-player-teleport': { char: '\uea6d', label: 'Player Teleport', category: 'player' },
  'ra-player-thunder-struck': { char: '\uea6e', label: 'Player Thunder Struck', category: 'player' },
  'ra-podium': { char: '\uea70', label: 'Podium', category: 'rpg' },
  'ra-poison-cloud': { char: '\uea71', label: 'Poison Cloud', category: 'dangers' },
  'ra-potion': { char: '\uea72', label: 'Potion', category: 'potions' },
  'ra-pyramids': { char: '\uea73', label: 'Pyramids', category: 'rpg' },
  'ra-queen-crown': { char: '\uea74', label: 'Queen Crown', category: 'armor' },
  'ra-quill-ink': { char: '\uea75', label: 'Quill Ink', category: 'inventory' },
  'ra-rabbit': { char: '\uea76', label: 'Rabbit', category: 'creatures' },
  'ra-radar-dish': { char: '\uea77', label: 'Radar Dish', category: 'electronics' },
  'ra-radial-balance': { char: '\uea78', label: 'Radial Balance', category: 'rpg' },
  'ra-radioactive': { char: '\uea79', label: 'Radioactive', category: 'electronics' },
  'ra-raven': { char: '\uea7a', label: 'Raven', category: 'creatures' },
  'ra-reactor': { char: '\uea7b', label: 'Reactor', category: 'electronics' },
  'ra-recycle': { char: '\uea7c', label: 'Recycle', category: 'electronics' },
  'ra-regeneration': { char: '\uea7d', label: 'Regeneration', category: 'electronics' },
  'ra-relic-blade': { char: '\uea7e', label: 'Relic Blade', category: 'weapons' },
  'ra-repair': { char: '\uea7f', label: 'Repair', category: 'electronics' },
  'ra-reverse': { char: '\uea80', label: 'Reverse', category: 'rpg' },
  'ra-revolver': { char: '\uea81', label: 'Revolver', category: 'weapons' },
  'ra-rifle': { char: '\uea82', label: 'Rifle', category: 'weapons' },
  'ra-ringing-bell': { char: '\uea83', label: 'Ringing Bell', category: 'inventory' },
  'ra-roast-chicken': { char: '\uea84', label: 'Roast Chicken', category: 'food' },
  'ra-robot-arm': { char: '\uea85', label: 'Robot Arm', category: 'electronics' },
  'ra-round-bottom-flask': { char: '\uea86', label: 'Round Bottom Flask', category: 'potions' },
  'ra-round-shield': { char: '\uea87', label: 'Round Shield', category: 'armor' },
  'ra-rss': { char: '\uea88', label: 'Rss', category: 'electronics' },
  'ra-rune-stone': { char: '\uea89', label: 'Rune Stone', category: 'magic' },
  'ra-sagittarius': { char: '\uea8a', label: 'Sagittarius', category: 'astrology' },
  'ra-sapphire': { char: '\uea8b', label: 'Sapphire', category: 'magic' },
  'ra-satellite': { char: '\uea8c', label: 'Satellite', category: 'electronics' },
  'ra-save': { char: '\uea8d', label: 'Save', category: 'electronics' },
  'ra-scorpio': { char: '\uea8e', label: 'Scorpio', category: 'astrology' },
  'ra-scroll-unfurled': { char: '\uea8f', label: 'Scroll Unfurled', category: 'magic' },
  'ra-scythe': { char: '\uea90', label: 'Scythe', category: 'weapons' },
  'ra-sea-serpent': { char: '\uea91', label: 'Sea Serpent', category: 'creatures' },
  'ra-seagull': { char: '\uea92', label: 'Seagull', category: 'creatures' },
  'ra-shark': { char: '\uea93', label: 'Shark', category: 'creatures' },
  'ra-sheep': { char: '\uea94', label: 'Sheep', category: 'creatures' },
  'ra-sheriff': { char: '\uea95', label: 'Sheriff', category: 'inventory' },
  'ra-shield': { char: '\uea96', label: 'Shield', category: 'armor' },
  'ra-ship-emblem': { char: '\uea97', label: 'Ship Emblem', category: 'inventory' },
  'ra-shoe-prints': { char: '\uea98', label: 'Shoe Prints', category: 'player' },
  'ra-shot-through-the-heart': { char: '\uea99', label: 'Shot Through The Heart', category: 'dangers' },
  'ra-shotgun-shell': { char: '\uea9a', label: 'Shotgun Shell', category: 'weapons' },
  'ra-shovel': { char: '\uea9b', label: 'Shovel', category: 'weapons' },
  'ra-shuriken': { char: '\uea9c', label: 'Shuriken', category: 'weapons' },
  'ra-sickle': { char: '\uea9d', label: 'Sickle', category: 'weapons' },
  'ra-sideswipe': { char: '\uea9e', label: 'Sideswipe', category: 'rpg' },
  'ra-site': { char: '\uea9f', label: 'Site', category: 'rpg' },
  'ra-skull': { char: '\ueaa1', label: 'Skull', category: 'dangers' },
  'ra-skull-trophy': { char: '\ueaa0', label: 'Skull Trophy', category: 'dangers' },
  'ra-slash-ring': { char: '\ueaa2', label: 'Slash Ring', category: 'inventory' },
  'ra-small-fire': { char: '\ueaa3', label: 'Small Fire', category: 'magic' },
  'ra-snail': { char: '\ueaa4', label: 'Snail', category: 'creatures' },
  'ra-snake': { char: '\ueaa5', label: 'Snake', category: 'creatures' },
  'ra-snorkel': { char: '\ueaa6', label: 'Snorkel', category: 'inventory' },
  'ra-snowflake': { char: '\ueaa7', label: 'Snowflake', category: 'magic' },
  'ra-soccer-ball': { char: '\ueaa8', label: 'Soccer Ball', category: 'inventory' },
  'ra-spades': { char: '\ueaaa', label: 'Spades', category: 'cards-dice' },
  'ra-spades-card': { char: '\ueaa9', label: 'Spades Card', category: 'cards-dice' },
  'ra-spawn-node': { char: '\ueaab', label: 'Spawn Node', category: 'rpg' },
  'ra-spear-head': { char: '\ueaac', label: 'Spear Head', category: 'weapons' },
  'ra-speech-bubble': { char: '\ueaad', label: 'Speech Bubble', category: 'electronics' },
  'ra-speech-bubbles': { char: '\ueaae', label: 'Speech Bubbles', category: 'electronics' },
  'ra-spider-face': { char: '\ueaaf', label: 'Spider Face', category: 'creatures' },
  'ra-spikeball': { char: '\ueab0', label: 'Spikeball', category: 'dangers' },
  'ra-spiked-mace': { char: '\ueab1', label: 'Spiked Mace', category: 'weapons' },
  'ra-spiked-tentacle': { char: '\ueab2', label: 'Spiked Tentacle', category: 'creatures' },
  'ra-spinning-sword': { char: '\ueab3', label: 'Spinning Sword', category: 'weapons' },
  'ra-spiral-shell': { char: '\ueab4', label: 'Spiral Shell', category: 'creatures' },
  'ra-splash': { char: '\ueab5', label: 'Splash', category: 'rpg' },
  'ra-spray-can': { char: '\ueab6', label: 'Spray Can', category: 'inventory' },
  'ra-sprout': { char: '\ueab8', label: 'Sprout', category: 'plants' },
  'ra-sprout-emblem': { char: '\ueab7', label: 'Sprout Emblem', category: 'plants' },
  'ra-stopwatch': { char: '\ueab9', label: 'Stopwatch', category: 'inventory' },
  'ra-suckered-tentacle': { char: '\ueaba', label: 'Suckered Tentacle', category: 'creatures' },
  'ra-suits': { char: '\ueabb', label: 'Suits', category: 'cards-dice' },
  'ra-sun': { char: '\ueabd', label: 'Sun', category: 'magic' },
  'ra-sun-symbol': { char: '\ueabc', label: 'Sun Symbol', category: 'magic' },
  'ra-sunbeams': { char: '\ueabe', label: 'Sunbeams', category: 'magic' },
  'ra-super-mushroom': { char: '\ueabf', label: 'Super Mushroom', category: 'plants' },
  'ra-supersonic-arrow': { char: '\ueac0', label: 'Supersonic Arrow', category: 'weapons' },
  'ra-surveillance-camera': { char: '\ueac1', label: 'Surveillance Camera', category: 'electronics' },
  'ra-sword': { char: '\ue946', label: 'Sword', category: 'weapons' },
  'ra-syringe': { char: '\ueac2', label: 'Syringe', category: 'inventory' },
  'ra-target-arrows': { char: '\ueac3', label: 'Target Arrows', category: 'weapons' },
  'ra-target-laser': { char: '\ueac4', label: 'Target Laser', category: 'rpg' },
  'ra-targeted': { char: '\ueac5', label: 'Targeted', category: 'rpg' },
  'ra-taurus': { char: '\ueac6', label: 'Taurus', category: 'astrology' },
  'ra-telescope': { char: '\ueac7', label: 'Telescope', category: 'electronics' },
  'ra-tentacle': { char: '\ueac8', label: 'Tentacle', category: 'creatures' },
  'ra-tesla': { char: '\ueac9', label: 'Tesla', category: 'electronics' },
  'ra-thorn-arrow': { char: '\ueaca', label: 'Thorn Arrow', category: 'weapons' },
  'ra-thorny-vine': { char: '\ueacb', label: 'Thorny Vine', category: 'plants' },
  'ra-three-keys': { char: '\ueacc', label: 'Three Keys', category: 'inventory' },
  'ra-tic-tac-toe': { char: '\ueacd', label: 'Tic Tac Toe', category: 'inventory' },
  'ra-toast': { char: '\ueace', label: 'Toast', category: 'food' },
  'ra-tombstone': { char: '\ueacf', label: 'Tombstone', category: 'dangers' },
  'ra-tooth': { char: '\uead0', label: 'Tooth', category: 'inventory' },
  'ra-torch': { char: '\uead1', label: 'Torch', category: 'inventory' },
  'ra-tower': { char: '\uead2', label: 'Tower', category: 'rpg' },
  'ra-trail': { char: '\uead3', label: 'Trail', category: 'rpg' },
  'ra-trefoil-lily': { char: '\uead4', label: 'Trefoil Lily', category: 'plants' },
  'ra-trident': { char: '\uead5', label: 'Trident', category: 'weapons' },
  'ra-triforce': { char: '\uead6', label: 'Triforce', category: 'magic' },
  'ra-trophy': { char: '\uead7', label: 'Trophy', category: 'inventory' },
  'ra-turd': { char: '\uead8', label: 'Turd', category: 'inventory' },
  'ra-two-dragons': { char: '\uead9', label: 'Two Dragons', category: 'creatures' },
  'ra-two-hearts': { char: '\ueada', label: 'Two Hearts', category: 'magic' },
  'ra-uncertainty': { char: '\ueadb', label: 'Uncertainty', category: 'rpg' },
  'ra-underhand': { char: '\ueadc', label: 'Underhand', category: 'rpg' },
  'ra-unplugged': { char: '\ueadd', label: 'Unplugged', category: 'electronics' },
  'ra-vase': { char: '\ueade', label: 'Vase', category: 'potions' },
  'ra-venomous-snake': { char: '\ueadf', label: 'Venomous Snake', category: 'creatures' },
  'ra-vest': { char: '\ueae0', label: 'Vest', category: 'armor' },
  'ra-vial': { char: '\ueae1', label: 'Vial', category: 'potions' },
  'ra-vine-whip': { char: '\ueae2', label: 'Vine Whip', category: 'weapons' },
  'ra-virgo': { char: '\ueae3', label: 'Virgo', category: 'astrology' },
  'ra-water-drop': { char: '\ueae4', label: 'Water Drop', category: 'magic' },
  'ra-wifi': { char: '\ueae5', label: 'Wifi', category: 'electronics' },
  'ra-wireless-signal': { char: '\ueae6', label: 'Wireless Signal', category: 'electronics' },
  'ra-wolf-head': { char: '\ueae7', label: 'Wolf Head', category: 'creatures' },
  'ra-wolf-howl': { char: '\ueae8', label: 'Wolf Howl', category: 'creatures' },
  'ra-wooden-sign': { char: '\ueae9', label: 'Wooden Sign', category: 'inventory' },
  'ra-wrench': { char: '\ueaea', label: 'Wrench', category: 'inventory' },
  'ra-wyvern': { char: '\ueaeb', label: 'Wyvern', category: 'creatures' },
  'ra-x-mark': { char: '\ueaec', label: 'X Mark', category: 'dangers' },
  'ra-zebra-shield': { char: '\ueaed', label: 'Zebra Shield', category: 'armor' },
  'ra-zigzag-leaf': { char: '\ueaee', label: 'Zigzag Leaf', category: 'plants' },
};

/**
 * Get the character for an icon class
 */
function getIconChar(iconClass: string): string | null {
  const icon = RA_ICONS[iconClass];
  return icon ? icon.char : null;
}

/**
 * Get full info for an icon
 */
function getIconInfo(iconClass: string): IconData | null {
  return RA_ICONS[iconClass] || null;
}

/**
 * Get all icons in a category
 */
function getIconsByCategory(categoryId: string): IconWithClass[] {
  return Object.entries(RA_ICONS)
    .filter(([_, data]) => data.category === categoryId)
    .map(([iconClass, data]) => ({ iconClass, ...data }));
}

/**
 * Search icons by label or class name
 */
function searchIcons(query: string): IconWithClass[] {
  const lowerQuery = query.toLowerCase();
  return Object.entries(RA_ICONS)
    .filter(([iconClass, data]) =>
      iconClass.toLowerCase().includes(lowerQuery) ||
      data.label.toLowerCase().includes(lowerQuery)
    )
    .map(([iconClass, data]) => ({ iconClass, ...data }));
}

/**
 * Get all icon class names
 */
function getAllIconClasses(): string[] {
  return Object.keys(RA_ICONS);
}

return {
  RA_CATEGORIES,
  RA_ICONS,
  getIconChar,
  getIconInfo,
  getIconsByCategory,
  searchIcons,
  getAllIconClasses
};
